<?php

namespace Tests\Unit;

use App\Models\MeterReadingsInitialize;
use App\Services\MeterReadingService;
use Tests\TestCase;

class MeterReadingServiceTest extends TestCase
{
    private static $meterReadingService;
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        MeterReadingServiceTest::$meterReadingService = new MeterReadingService();
    }

    /**
     * @test
     */
    public function should_Return_Readings_For_Valid_Meter_Id()
    {
        $readings = MeterReadingServiceTest::$meterReadingService->getReadings("smart-meter-1");
        $this->assertCount(2, $readings);
    }

    /**
     * @test
     */
    public function should_Return_Empty_Array_For_Invalid_Meter_Id()
    {
        $readings = MeterReadingServiceTest::$meterReadingService->getReadings("unknown-id");
        $this->assertCount(0, $readings);
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}
