<?php

namespace Tests\Unit;

use App\Models\MeterReadingsInitialize;
use App\Services\MeterReadingService;
use PHPUnit\Framework\TestCase;

class MeterReadingServiceTest extends TestCase
{
    /**
     * Test the read Meter Readings endpoint
     *
     * @return
     */
    private static $meterReadingService;
    private static $meterReadingInitialize;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        MeterReadingServiceTest::$meterReadingInitialize = new MeterReadingsInitialize();
        MeterReadingServiceTest::$meterReadingService = new MeterReadingService(MeterReadingServiceTest::$meterReadingInitialize);
    }

    public function test_getMeterReadings()
    {
        $readings = MeterReadingServiceTest::$meterReadingService->getReadings("smart-meter-1");
        $this->assertEquals(5, count($readings)); // TBD Assert count
    }

    public function test_storeMeterReadings()
    {
        $readings = MeterReadingServiceTest::$meterReadingService->getReadings("smart-meter-1");
        print_r($readings);
        $this->assertCount(2, $readings);
    }
    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}
